number1 = int(input("Enter number1: "))
number2 = int(input("Enter number2: "))
print(number1 + number2)
print(number1 - number2)
print(number1 * number2)
print(number1 / number2)
print(number1 // number2)